apiVersion: apps/v1
kind: Deployment
metadata:
  name: podpreset-webhook-deployment
  labels:
    app: podpreset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podpreset
  template:
    metadata:
      labels:
        app: podpreset
    spec:
      containers:
      - name: podpreset-webhook
        imagePullPolicy: IfNotPresent
        image: docker.io/service-catalog/admission-webhook:latest
        args:
        - -tls-cert-file=/keys/tls.crt
        - -tls-private-key-file=/keys/tls.key
        - -alsologtostderr
        - -v=6
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls-keys
          mountPath: /keys
      volumes:
      - name: tls-keys
        secret:
          secretName: podpreset-service-tls
---
kind: Service
apiVersion: v1
metadata:
  name: podpreset-service
spec:
  selector:
    app: podpreset
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: podpreset-webook-configuration
webhooks:
  - name: podpresets.settings.servicecatalog.k8s.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Ignore
    clientConfig:
      # base64 -w 0 ca.pem
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6RENDQXJTZ0F3SUJBZ0lVY2lNQjJwdHB2MjdvTVIybGtLUWhjRVc3eTFZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZqRUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGxOdmRYUm9JRU5oY205c2FXNWhNUkV3RHdZRApWUVFIRXdoRGIyeDFiV0pwWVRFYU1CZ0dBMVVFQ2hNUmNHOWtjSEpsYzJWMExYTmxjblpwWTJVeEN6QUpCZ05WCkJBc1RBa05CTVJvd0dBWURWUVFERXhGd2IyUndjbVZ6WlhRdGMyVnlkbWxqWlRBZUZ3MHhPREEyTVRNeU1qRTAKTURCYUZ3MHlNekEyTVRJeU1qRTBNREJhTUg0eEN6QUpCZ05WQkFZVEFsVlRNUmN3RlFZRFZRUUlFdzVUYjNWMAphQ0JEWVhKdmJHbHVZVEVSTUE4R0ExVUVCeE1JUTI5c2RXMWlhV0V4R2pBWUJnTlZCQW9URVhCdlpIQnlaWE5sCmRDMXpaWEoyYVdObE1Rc3dDUVlEVlFRTEV3SkRRVEVhTUJnR0ExVUVBeE1SY0c5a2NISmxjMlYwTFhObGNuWnAKWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURDVEJMNkFCTDVMVzBGQ3gvagp0VGUySmpLanJOTWRIOWlHL3dOdHJYd2txcU9HTDJlaXFOa3k2L0xSSVFKSHppdVE4ZUZPSldSZWpwblZvTEtkClg1c2F3SDNIcmIvcitURXdBbkd4bmlYc2VoaDNBY2hKbVRWdkVBYWVQWE83ZHBuYkRPVjRtOGljQW4zekFJL2YKOTV5c3Q2TDdaaStpR2lFRVVwTHdDNnc5TmFtaUZhOHRZZUhKLzdOZ25tVUc3cExhNXI3MDgwbUhoSkY5T2d4dwpWektwNk1ubjBwRXZHT0UxdUN6VW56aGRSb1M4dktGQTRYZDZHV1hzckNUVEpjS1lya2ZmNWlCUVV5M3lUTXFsCnVYMWQ0VGlaZFdqL1pjT01GQ1JnNTdDSnRWcytCbEpWd3lDSFQvTWhONGR4NWpWeVZDTFhGZmUvUzViMzBHRlkKQjFGQkFnTUJBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwRwpBMVVkRGdRV0JCUTlHdklpSHdHc1pOUUtIT0JkVlJZSVlNR3ZTakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkxIc0pVM1lKQVMxbm03dUVwTkRRRFBiZnpxTGxta015bFY1WEFURGg0WDVLMVUvRW1iQWZISmJlMGd4NjI5U1IKWXg3TG51WERRQmFXanZMMGFjcnJQdXlLekdUYk5hUElFSkZEbk1EZnEvYUZvc2NuWXNIWmVld0lTS2dBR3Mvcgo2VlR3NERaZm5wZS9Odk1OVUhJTmNIanRYVDJxYTJpRWJ5a2E3Q2gwK0M0cDd0Q1l4ZTgvTXYvRDZSUTRRWFFNCi9aMFRYc0xKZmJranRkL2ZVSktvaFpPOVJ0SWN5cDhZb2piL29RVzFrZmJjNlNoSnV5LzRrNjZRKzlvVnhNRlYKOUpiNnVnbzFLbC9HTVF2MWxZMmdTUDlzNjA5YnY4cytKYW9UQ2dzWG93TGtrU1hKcWxqRU1qc0Z0djZEZ2ttSgpNc21BTG1OOUlMdFdxT2tCNHh5UFVnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: podpreset-service
        namespace: default
        path: "/mutating-pods"
